config/routes.rb
Cure::Application.routes.draw do
  resources :user_supplements

  resources :supplement_plans

  resources :supplements

  resources :supplement_groups

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/supplement.rb
class Supplement < ActiveRecord::Base
  attr_accessible :description, :dose, :name, :supplement_group_id
end

app/controllers/supplements_controller.rb
class SupplementsController < ApplicationController
  # GET /supplements
  # GET /supplements.json
  def index
    @supplements = Supplement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @supplements }
    end
  end

  # GET /supplements/1
  # GET /supplements/1.json
  def show
    @supplement = Supplement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @supplement }
    end
  end

  # GET /supplements/new
  # GET /supplements/new.json
  def new
    @supplement = Supplement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @supplement }
    end
  end

  # GET /supplements/1/edit
  def edit
    @supplement = Supplement.find(params[:id])
  end

  # POST /supplements
  # POST /supplements.json
  def create
    @supplement = Supplement.new(params[:supplement])

    respond_to do |format|
      if @supplement.save
        format.html { redirect_to @supplement, notice: 'Supplement was successfully created.' }
        format.json { render json: @supplement, status: :created, location: @supplement }
      else
        format.html { render action: "new" }
        format.json { render json: @supplement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /supplements/1
  # PUT /supplements/1.json
  def update
    @supplement = Supplement.find(params[:id])

    respond_to do |format|
      if @supplement.update_attributes(params[:supplement])
        format.html { redirect_to @supplement, notice: 'Supplement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @supplement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplements/1
  # DELETE /supplements/1.json
  def destroy
    @supplement = Supplement.find(params[:id])
    @supplement.destroy

    respond_to do |format|
      format.html { redirect_to supplements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/supplements_helper.rb
module SupplementsHelper
end

app/views/supplements/_form.html.haml
= simple_form_for(@supplement) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :supplement_group_id
    = f.input :description
    = f.input :dose

  .form-actions
    = f.button :submit

app/views/supplements/edit.html.haml
%h1 Editing supplement

= render 'form'

= link_to 'Show', @supplement
\|
= link_to 'Back', supplements_path

app/views/supplements/index.html.haml
%h1 Listing supplements

%table
  %tr
    %th Name
    %th Supplement group
    %th Description
    %th Dose
    %th
    %th
    %th

  - @supplements.each do |supplement|
    %tr
      %td= supplement.name
      %td= supplement.supplement_group_id
      %td= supplement.description
      %td= supplement.dose
      %td= link_to 'Show', supplement
      %td= link_to 'Edit', edit_supplement_path(supplement)
      %td= link_to 'Destroy', supplement, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Supplement', new_supplement_path

app/views/supplements/new.html.haml
%h1 New supplement

= render 'form'

= link_to 'Back', supplements_path

app/views/supplements/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @supplement.name
%p
  %b Supplement group:
  = @supplement.supplement_group_id
%p
  %b Description:
  = @supplement.description
%p
  %b Dose:
  = @supplement.dose

= link_to 'Edit', edit_supplement_path(@supplement)
\|
= link_to 'Back', supplements_path