config/routes.rb
Cure::Application.routes.draw do
  resources :user_supplements

  resources :supplement_plans

  resources :supplements

  resources :supplement_groups

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/supplement_group.rb
class SupplementGroup < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/supplement_groups_controller.rb
class SupplementGroupsController < ApplicationController
  # GET /supplement_groups
  # GET /supplement_groups.json
  def index
    @supplement_groups = SupplementGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @supplement_groups }
    end
  end

  # GET /supplement_groups/1
  # GET /supplement_groups/1.json
  def show
    @supplement_group = SupplementGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @supplement_group }
    end
  end

  # GET /supplement_groups/new
  # GET /supplement_groups/new.json
  def new
    @supplement_group = SupplementGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @supplement_group }
    end
  end

  # GET /supplement_groups/1/edit
  def edit
    @supplement_group = SupplementGroup.find(params[:id])
  end

  # POST /supplement_groups
  # POST /supplement_groups.json
  def create
    @supplement_group = SupplementGroup.new(params[:supplement_group])

    respond_to do |format|
      if @supplement_group.save
        format.html { redirect_to @supplement_group, notice: 'Supplement group was successfully created.' }
        format.json { render json: @supplement_group, status: :created, location: @supplement_group }
      else
        format.html { render action: "new" }
        format.json { render json: @supplement_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /supplement_groups/1
  # PUT /supplement_groups/1.json
  def update
    @supplement_group = SupplementGroup.find(params[:id])

    respond_to do |format|
      if @supplement_group.update_attributes(params[:supplement_group])
        format.html { redirect_to @supplement_group, notice: 'Supplement group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @supplement_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplement_groups/1
  # DELETE /supplement_groups/1.json
  def destroy
    @supplement_group = SupplementGroup.find(params[:id])
    @supplement_group.destroy

    respond_to do |format|
      format.html { redirect_to supplement_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/supplement_groups_helper.rb
module SupplementGroupsHelper
end

app/views/supplement_groups/_form.html.haml
= simple_form_for(@supplement_group) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/supplement_groups/edit.html.haml
%h1 Editing supplement_group

= render 'form'

= link_to 'Show', @supplement_group
\|
= link_to 'Back', supplement_groups_path

app/views/supplement_groups/index.html.haml
%h1 Listing supplement_groups

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @supplement_groups.each do |supplement_group|
    %tr
      %td= supplement_group.name
      %td= supplement_group.description
      %td= link_to 'Show', supplement_group
      %td= link_to 'Edit', edit_supplement_group_path(supplement_group)
      %td= link_to 'Destroy', supplement_group, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Supplement group', new_supplement_group_path

app/views/supplement_groups/new.html.haml
%h1 New supplement_group

= render 'form'

= link_to 'Back', supplement_groups_path

app/views/supplement_groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @supplement_group.name
%p
  %b Description:
  = @supplement_group.description

= link_to 'Edit', edit_supplement_group_path(@supplement_group)
\|
= link_to 'Back', supplement_groups_path