config/routes.rb
Cure::Application.routes.draw do
  resources :user_supplements

  resources :supplement_plans

  resources :supplements

  resources :supplement_groups

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/user_supplement.rb
class UserSupplement < ActiveRecord::Base
  attr_accessible :plan_id, :supplement_id
end

app/controllers/user_supplements_controller.rb
class UserSupplementsController < ApplicationController
  # GET /user_supplements
  # GET /user_supplements.json
  def index
    @user_supplements = UserSupplement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_supplements }
    end
  end

  # GET /user_supplements/1
  # GET /user_supplements/1.json
  def show
    @user_supplement = UserSupplement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_supplement }
    end
  end

  # GET /user_supplements/new
  # GET /user_supplements/new.json
  def new
    @user_supplement = UserSupplement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_supplement }
    end
  end

  # GET /user_supplements/1/edit
  def edit
    @user_supplement = UserSupplement.find(params[:id])
  end

  # POST /user_supplements
  # POST /user_supplements.json
  def create
    @user_supplement = UserSupplement.new(params[:user_supplement])

    respond_to do |format|
      if @user_supplement.save
        format.html { redirect_to @user_supplement, notice: 'User supplement was successfully created.' }
        format.json { render json: @user_supplement, status: :created, location: @user_supplement }
      else
        format.html { render action: "new" }
        format.json { render json: @user_supplement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_supplements/1
  # PUT /user_supplements/1.json
  def update
    @user_supplement = UserSupplement.find(params[:id])

    respond_to do |format|
      if @user_supplement.update_attributes(params[:user_supplement])
        format.html { redirect_to @user_supplement, notice: 'User supplement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_supplement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_supplements/1
  # DELETE /user_supplements/1.json
  def destroy
    @user_supplement = UserSupplement.find(params[:id])
    @user_supplement.destroy

    respond_to do |format|
      format.html { redirect_to user_supplements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_supplements_helper.rb
module UserSupplementsHelper
end

app/views/user_supplements/_form.html.haml
= simple_form_for(@user_supplement) do |f|
  = f.error_notification

  .form-inputs
    = f.input :plan_id
    = f.input :supplement_id

  .form-actions
    = f.button :submit

app/views/user_supplements/edit.html.haml
%h1 Editing user_supplement

= render 'form'

= link_to 'Show', @user_supplement
\|
= link_to 'Back', user_supplements_path

app/views/user_supplements/index.html.haml
%h1 Listing user_supplements

%table
  %tr
    %th Plan
    %th Supplement
    %th
    %th
    %th

  - @user_supplements.each do |user_supplement|
    %tr
      %td= user_supplement.plan_id
      %td= user_supplement.supplement_id
      %td= link_to 'Show', user_supplement
      %td= link_to 'Edit', edit_user_supplement_path(user_supplement)
      %td= link_to 'Destroy', user_supplement, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User supplement', new_user_supplement_path

app/views/user_supplements/new.html.haml
%h1 New user_supplement

= render 'form'

= link_to 'Back', user_supplements_path

app/views/user_supplements/show.html.haml
%p#notice= notice

%p
  %b Plan:
  = @user_supplement.plan_id
%p
  %b Supplement:
  = @user_supplement.supplement_id

= link_to 'Edit', edit_user_supplement_path(@user_supplement)
\|
= link_to 'Back', user_supplements_path