config/routes.rb
Cure::Application.routes.draw do
  resources :user_supplements

  resources :supplement_plans

  resources :supplements

  resources :supplement_groups

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/supplement_plan.rb
class SupplementPlan < ActiveRecord::Base
  attr_accessible :description, :name, :user_id
end

app/controllers/supplement_plans_controller.rb
class SupplementPlansController < ApplicationController
  # GET /supplement_plans
  # GET /supplement_plans.json
  def index
    @supplement_plans = SupplementPlan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @supplement_plans }
    end
  end

  # GET /supplement_plans/1
  # GET /supplement_plans/1.json
  def show
    @supplement_plan = SupplementPlan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @supplement_plan }
    end
  end

  # GET /supplement_plans/new
  # GET /supplement_plans/new.json
  def new
    @supplement_plan = SupplementPlan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @supplement_plan }
    end
  end

  # GET /supplement_plans/1/edit
  def edit
    @supplement_plan = SupplementPlan.find(params[:id])
  end

  # POST /supplement_plans
  # POST /supplement_plans.json
  def create
    @supplement_plan = SupplementPlan.new(params[:supplement_plan])

    respond_to do |format|
      if @supplement_plan.save
        format.html { redirect_to @supplement_plan, notice: 'Supplement plan was successfully created.' }
        format.json { render json: @supplement_plan, status: :created, location: @supplement_plan }
      else
        format.html { render action: "new" }
        format.json { render json: @supplement_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /supplement_plans/1
  # PUT /supplement_plans/1.json
  def update
    @supplement_plan = SupplementPlan.find(params[:id])

    respond_to do |format|
      if @supplement_plan.update_attributes(params[:supplement_plan])
        format.html { redirect_to @supplement_plan, notice: 'Supplement plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @supplement_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplement_plans/1
  # DELETE /supplement_plans/1.json
  def destroy
    @supplement_plan = SupplementPlan.find(params[:id])
    @supplement_plan.destroy

    respond_to do |format|
      format.html { redirect_to supplement_plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/supplement_plans_helper.rb
module SupplementPlansHelper
end

app/views/supplement_plans/_form.html.haml
= simple_form_for(@supplement_plan) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/supplement_plans/edit.html.haml
%h1 Editing supplement_plan

= render 'form'

= link_to 'Show', @supplement_plan
\|
= link_to 'Back', supplement_plans_path

app/views/supplement_plans/index.html.haml
%h1 Listing supplement_plans

%table
  %tr
    %th User
    %th Name
    %th Description
    %th
    %th
    %th

  - @supplement_plans.each do |supplement_plan|
    %tr
      %td= supplement_plan.user_id
      %td= supplement_plan.name
      %td= supplement_plan.description
      %td= link_to 'Show', supplement_plan
      %td= link_to 'Edit', edit_supplement_plan_path(supplement_plan)
      %td= link_to 'Destroy', supplement_plan, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Supplement plan', new_supplement_plan_path

app/views/supplement_plans/new.html.haml
%h1 New supplement_plan

= render 'form'

= link_to 'Back', supplement_plans_path

app/views/supplement_plans/show.html.haml
%p#notice= notice

%p
  %b User:
  = @supplement_plan.user_id
%p
  %b Name:
  = @supplement_plan.name
%p
  %b Description:
  = @supplement_plan.description

= link_to 'Edit', edit_supplement_plan_path(@supplement_plan)
\|
= link_to 'Back', supplement_plans_path